{
    "version": "2",
    "volumes": {
        "postgres_data": {
            "driver": "local"
        }
    },
    "services": {
        "postgres": {
            "image": "postgres",
            "volumes": [
                "postgres_data:/var/lib/postgresql/data"
            ]
        },
        "apache": {
            "build": {
                "context": ".",
                "dockerfile": "Dockerfile-apache+postgres"
            },
            "volumes": [
                "./:/var/www/html"
            ],
            "links": [
                "postgres"
            ],
            "depends_on": [
                "postgres"
            ]
        },
        "nginx": {
            "image": "nginx:alpine",
            "volumes": [
                "./:/var/www",
                "./nginx.apache.conf:/etc/nginx/nginx.conf:ro"
            ],
            "links": [
                "apache"
            ],
            "ports": [
                "80:80"
            ],
            "depends_on": [
                "apache"
            ]
        }
    }
}
